### ISSUE TITLE
Web Config

### ISSUE THREAD

**Issue by daktak** [Zwater/zackwatch-public#5]
https://github.com/daktak/daktak.github.io/tree/master/zackwatch-config

I see you've been working on zwater.no-ip.org.

I had ago above, but looks like yours is coming along nicely, check out main.js if you need, I just got toggles working

**Comment by Zwater** [comment]
Yeah, it almost looks like yours is nicer because you've split the
javascript off into its own file. I was working on implementing the refresh
interval last night but was running into an error and went to bed.

This could end up a little weird because you and I appear to be adding the
exact same stuff at the same time to our respective repositories, with
slightly different methods of implementation.

**Comment by daktak** [comment]
Ok, it seems that the variables in the C have to be persisted.
I beleive I have most working
I'm happy with my people resizing

**Comment by daktak** [comment]
Just got 5 ppl working! :-)
Also fixed my problem with updating people , so now works for all , checks first before redrawing, thus hopefully saving battery
